---

- hosts: arista 
  gather_facts: false
  connection: local

  tasks:

  - name: remove acl named 'test' on remote arista devices
    eos_config:
        lines:
          - no ip access-list test
        provider: '{{ eos_connection }}'

  - name: verify acl named 'test' successfully removed via 'show ip access-lists test'
    eos_command:
         commands:
          - show ip access-lists test
         provider: '{{ eos_connection }}'

  - name: save running-config to startup-config
    eos_config:
        save_when: modified
        provider: '{{ eos_connection }}'


# To enable networking debug
# 1. Enable 'log_path=/var/log/ansible.log' in ansible.cfg file
# 2. Specify the location for the log file
#    export ANSIBLE_LOG_PATH=~/ansible.log
# 3. Enable Debug
#    export ANSIBLE_DEBUG=True
# 4. Run with 4*v for connection level verbosity
#    ansible-playbook -vvvv ...
